import {
	AntDesignOutlined,
	ApartmentOutlined,
	AppstoreOutlined,
	CloudOutlined,
	ContainerOutlined,
	CopyrightOutlined,
	DashboardOutlined,
	DeleteOutlined,
	EyeOutlined,
	FileTextOutlined,
	GlobalOutlined,
	HomeOutlined,
	ImportOutlined,
	LockOutlined,
	MailOutlined,
	MenuOutlined,
	NodeExpandOutlined,
	PaperClipOutlined,
	SafetyCertificateOutlined,
	SafetyOutlined,
	SettingOutlined,
	SisternodeOutlined,
	SolutionOutlined,
	SubnodeOutlined,
	TeamOutlined,
	UserAddOutlined,
	UserDeleteOutlined,
	UserOutlined,
} from "@ant-design/icons";
import { EmbeddedIcon, ExternalIcon, OutsidePageIcon, ProfileCardIcon } from "./local-icons";
import { RiAccountCircleLine, RiReactjsLine, RiUserSettingsLine } from "./ri";

/**
 * Icons used in the menu.
 */
export const menuIcons: Record<string, any> = {
	AppstoreOutlined,
	EmbeddedIcon,
	HomeOutlined,
	DashboardOutlined,
	SafetyOutlined,
	SafetyCertificateOutlined,
	CloudOutlined,
	FileTextOutlined,
	LockOutlined,
	EyeOutlined,
	NodeExpandOutlined,
	SisternodeOutlined,
	SubnodeOutlined,
	OutsidePageIcon,
	AntDesignOutlined,
	ContainerOutlined,
	ExternalIcon,
	RiReactjsLine,
	SettingOutlined,
	UserOutlined,
	UserAddOutlined,
	UserDeleteOutlined,
	TeamOutlined,
	MenuOutlined,
	ApartmentOutlined,
	GlobalOutlined,
	ImportOutlined,
	SolutionOutlined,
	MailOutlined,
	PaperClipOutlined,
	DeleteOutlined,
	RiAccountCircleLine,
	ProfileCardIcon,
	RiUserSettingsLine,
	CopyrightOutlined,
};
