-- 业务端一级菜单补齐侧栏图标（Ant Design Outlined 组件名，须在前端 menu-icons 注册）

UPDATE iam_admin_menu
SET icon = CASE code
    WHEN 'BUSINESS-HOME-MENU' THEN 'HomeOutlined'
    WHEN 'BUSINESS-DOMAIN-OVERVIEW' THEN 'DashboardOutlined'
    WHEN 'BUSINESS-DOMAIN-BASIC' THEN 'SettingOutlined'
    WHEN 'BUSINESS-DOMAIN-MEMBERS' THEN 'TeamOutlined'
    WHEN 'BUSINESS-DOMAIN-ROLES' THEN 'SafetyCertificateOutlined'
    WHEN 'BUSINESS-DOMAIN-CUSTOMERS' THEN 'SolutionOutlined'
    WHEN 'BUSINESS-DOMAIN-ONBOARDING' THEN 'UserAddOutlined'
    WHEN 'BUSINESS-DOMAIN-TICKET-CONFIG' THEN 'AppstoreOutlined'
    WHEN 'BUSINESS-DOMAIN-BLOCKWORDS' THEN 'StopOutlined'
    WHEN 'BUSINESS-DOMAIN-NOTIFICATIONS' THEN 'MailOutlined'
    WHEN 'BUSINESS-DOMAIN-CONFIG' THEN 'ControlOutlined'
    WHEN 'BUSINESS-DOMAIN-AUDIT-LOGS' THEN 'FileTextOutlined'
    WHEN 'BUSINESS-DOMAIN-LOGIN-LOGS' THEN 'LoginOutlined'
    ELSE icon
END,
    updated_at = CURRENT_TIMESTAMP(3)
WHERE scope = 'business'
  AND node_type = 'menu'
  AND code IN (
      'BUSINESS-HOME-MENU',
      'BUSINESS-DOMAIN-OVERVIEW',
      'BUSINESS-DOMAIN-BASIC',
      'BUSINESS-DOMAIN-MEMBERS',
      'BUSINESS-DOMAIN-ROLES',
      'BUSINESS-DOMAIN-CUSTOMERS',
      'BUSINESS-DOMAIN-ONBOARDING',
      'BUSINESS-DOMAIN-TICKET-CONFIG',
      'BUSINESS-DOMAIN-BLOCKWORDS',
      'BUSINESS-DOMAIN-NOTIFICATIONS',
      'BUSINESS-DOMAIN-CONFIG',
      'BUSINESS-DOMAIN-AUDIT-LOGS',
      'BUSINESS-DOMAIN-LOGIN-LOGS'
  );
