spring:
  application:
    name: uniondesk
  datasource:
    url: jdbc:mysql://127.0.0.1:30306/uniondesk?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: uniondesk_app
    password: gq0fd2sqOCncrNp3eBeGuLty
  flyway:
    enabled: true
    validate-on-migrate: false
    locations: classpath:db/migration/current

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

uniondesk:
  security:
    jwt:
      issuer: uniondesk
      secret: uniondesk-demo-jwt-secret-please-change-me
      access-token-ttl: PT24H
      refresh-token-ttl: P7D
